# @project      Scenamatica ${project.version}
# @author       Peyang <https://peya.tokyo>
# @license      The MIT License (MIT) <https://opensource.org/licenses/MIT>

# ------------[ インターフェース設定 ]------------
# Scenamatica のインターフェースの設定を定義します。
# --------------------------------------------
interfaces:
  # インターフェースの言語です。
  # デフォルトでは以下の言語に対応しています。
  # 日本語    - ja_JP
  # English  - en_US
  # 関西弁    - ja_KS
  lang: "ja_JP"

# ---------------[ シナリオ設定 ]---------------
# シナリオの設定を定義します。
# --------------------------------------------
scenario:
  # シナリオを実行するかどうかを設定します。
  # この設定が無効の場合, シナリオはスケジュールされず, 自動実行は行われず, 手動実行はエラーを出力します。
  # また, この設定は ゲーム内の /scenamatica enable コマンドによってオーバライドできます（コンフィグは書き換えられません）。
  enabled: true
  # シナリオの実行を無視するトリガの種類を設定します。
  # 例： ignoreTriggers: [ ON_LOAD ]
  # また, この設定はシステム・プロパティの org.kunlab.scenamatica.trigger.ignores に "," 区切りで設定してオーバライドできます。
  ignoreTriggers: []

# ---------------[ アクター設定 ]---------------
# アクターの設定を定義します。
# --------------------------------------------
actor:
  # アクターの最大数を設定します。
  # これ以上のアクターを作成するとエラーを出力します。
  maxActors: 100
  # アクターに与えるデフォルトの OP レベルを設定します。
  # これはシナリオファイルによって上書きされることがあります。
  # OP レベルの一覧：
  # - 0 - 通常のプレイヤーです。 OP はありません。
  # - 1 - スポーン範囲制限を無視できます。
  # - 2 - ちょっと多くのコマンドを使えます。コマンドブロックも使えます。
  # - 3 - もっといっぱいコマンド使えます。
  # - 4 - 全部のコマンド使えます。
  defaultOP: 4
  # アクターに与えるデフォルトの権限を設定します。
  # これはシナリオファイルによって上書きされることがあります。
  permissions:
  # アクターに与えるスコアボードのタグを設定します。
  # これはシナリオファイルによって上書きされることがあります。
  scoreboardTags:

# ---------------[ レポート設定 ]---------------
# レポートの設定を定義します。
# --------------------------------------------
reporting:
  # JSON でテスト結果を出力するかどうかを設定します。
  # 外部のツールでテスト結果を解析する場合に有効です。
  # JSON は、 stdout に出力されます。
  raw: false

  # シナリオランナの詳細なログや, テストの詳細なステップログを出力するかどうかを設定します。
  # raw モードが有効な場合, この設定は無視されます。
  # 注意： これが有効な場合、サーバのターミナルに大量のログが出力されます。
  #       デフォルトではかっこいいので有効にしていますが、ログが冗長だと感じたら無効にしてください。
  verbose: true
  # JUnit Result XML と呼ばれるデファクトスタンダードのテスト結果フォーマットで出力します。
  junit:
    # JUnit レポートを出力するかどうかを設定します。
    enabled: true
    # レポートの出力先を設定します。
    # Scenamatica のデータフォルダ(e.g. `plugins/Scenamatica`) からの相対パスで指定します。
    directory: "reports/"
    # レポートのファイル名のパターンを設定します。
    # 以下のプレースホルダを使用できます。
    # - {dateTime} - レポートを生成した日時。 (YYYY-MM-DD-hh-mm-ss)
    filePattern: "scenamatica-test-report-{dateTime}.xml"
