# @project      Scenamatica ${project.version}
# @author       Peyang <https://peya.tokyo>
# @license      The MIT License (MIT) <https://opensource.org/licenses/MIT>

# ------------[ インターフェース設定 ]------------
# Scenamatica のインターフェースの設定を定義します。
# --------------------------------------------
interfaces:
  # インターフェースの言語です。
  # デフォルトでは以下の言語に対応しています。
  # 日本語    - ja_JP
  # English  - en_US
  # 関西弁    - ja_KS
  lang: "ja_JP"

# ---------------[ シナリオ設定 ]---------------
# シナリオの設定を定義します。
# --------------------------------------------
scenario:
  # シナリオを実行するかどうかを設定します。
  # この設定が無効の場合, シナリオはスケジュールされず, 自動実行は行われず, 手動実行はエラーを出力します。
  # また, この設定は ゲーム内の /scenamatica enable コマンドによってオーバライドできます（コンフィグは書き換えられません）。
  enabled: true
