version: 2

updates:
  - package-ecosystem: maven
    directory: "Scenamatica/"
    schedule:
      interval: daily
      time: "20:00"
    open-pull-requests-limit: 10
    target-branch: develop
    labels:
      - "Type: Dependencies"
  - package-ecosystem: npm
    directory: "docs/"
    schedule:
      interval: daily
      time: "20:00"
    open-pull-requests-limit: 10
    target-branch: develop
    labels:
      - "Type: Dependencies"
