name: Build NMS with NMSAction
on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  build:
    name: Build with Maven
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Change directory to scenamatica
        run: cd Scenamatica
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        id: maven-cache
        with:
          java-version: 8
          distribution: zulu
          cache: maven
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2
      - name: Restore NMS cache
        uses: actions/cache@v4
        with:
          path: nms-build/.m2
          key: nms-maven
          restore-keys: nms-maven
      - name: Deploy NMS cache
        if: steps.maven-cache.outputs.cache-hit != 'true'
        run: |
          mv -f nms-build/.m2/repository $HOME/.m2/ -v
      - name: Build with Maven
        run: |
          cd Scenamatica
          chmod +x build.sh
          ./build.sh -D"jar.finalName=Scenamatica" -P debug
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: scenamatica
          path: Scenamatica/ScenamaticaPlugin/target/Scenamatica.jar
          retention-days: 1
          if-no-files-found: error
