name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main
    paths: 
      - docs/**
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Change directory to scenamatica
        run: cd Scenamatica
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: 22
          distribution: zulu
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2
      ##### NMS 以外のキャッシュを利かせる #####
      - name: Try to restore cache
        uses: actions/cache/restore@v4
        id: restore-cache
        with:
          key: maven-cache-${{ hashFiles('**/pom.xml') }}
          path: ~/.m2/repository
          enableCrossOsArchive: true
      - name: Collect dependencies without NMS
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: |
          mvn dependency:go-offline -f Scenamatica/pom.xml
          mvn dependency:go-offline -f Bookkeeper/pom.xml
        # 失敗することが前提なので↓
        continue-on-error: true
      - name: Cache dependencies without NMS
        if: steps.restore-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        id: cache-dependencies
        with:
          key: maven-cache-${{ hashFiles('**/pom.xml') }}
          path: ~/.m2/repository
          enableCrossOsArchive: true
      ##### おわり of NMS 以外のキャッシュを利かせる #####
      - name: Deploy NMS
        uses: TeamKun/NMSAccess@v2
        with:
          access-token: ${{ secrets.token }}
          versions: |
            1.18.1  # v1_18_R1
            1.18.1  # v1_18_R1
            1.17.1  # v1_17_R1
            1.16.5  # v1_16_R3
            1.16.3  # v1_16_R2
            1.16.1  # v1_16_R1
            1.15.2  # v1_15_R1
            1.14.4  # v1_14_R1
            1.13.2  # v1_13_R2
            1.13    # v1_13_R1
      - name: Change directory to root
        run: cd ..
      - run: chmod -R +x docs/
      - uses: chrnorm/deployment-action@v2
        name: Create GitHub Deployment
        id: deploy-status
        with:
          token: ${{ github.token }}
          environment-url: https://scenamatica.kunlab.org
          environment: production
          initial-status: in_progress
      - name: pnpm-setup
        uses: pnpm/action-setup@v3
        with: 
          package_json_file: docs/package.json
      - name: Install dependencies
        run:  |
          cd docs 
          pnpm install
          cd ..
      - name: Build
        run: |
          cd docs
          pnpm run build
          cd ..
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "docs/build/"
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
      - name: Update GitHub Deployment
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ github.token }}
          deployment-id: ${{ steps.deploy-status.outputs.deployment_id }}
          state: success
          environment-url: https://scenamatica.kunlab.org
          environment: production
      - name: Update GitHub Deployment
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ github.token }}
          deployment-id: ${{ steps.deploy-status.outputs.deployment_id }}
          state: failure
          environment-url: https://scenamatica.kunlab.org
      - name: Update GitHub Deployment
        if: cancelled()
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ github.token }}
          deployment-id: ${{ steps.deploy-status.outputs.deployment_id }}
          state: cancelled
          environment-url: https://scenamatica.kunlab.org
