name: Publish to HangarMC
on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to HangarMC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get the url of the artifact url from release assets
        id: get_asset_url
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const assets = await github.rest.repos.listReleaseAssets({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: context.payload.release.id
            });
            // Find the asset with the name ending with .jar
            const asset = assets.data.find(asset => asset.name.endsWith('.jar'));
            if (!asset) {
              throw new Error('No asset found');
            }
            
            return asset.browser_download_url;

      - name: Publish to HangarMC
        uses: benwoo1110/hangar-upload-action@v1
        with:
          api_token: ${{ secrets.HANGAR_TOKEN }}
          slug: Scenamatica
          version: ${{ github.event.release.tag_name }}
          channel: ${{ github.event.release.prerelease == true && 'Beta' || 'Release' }}
          files: |
            [
              {
                "platform": "PAPER",
                "url": true,
                "externalUrl": "${{ steps.get_asset_url.outputs.result }}"
              }
            ]
          description: ${{ github.event.release.body }}
