name: Qodana analysis
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  qodana:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2
      - uses: PeyaPeyaPeyang/nmsaction@v3
        if: "steps.sj.outputs.cache-hit != 'true'"
        with:
          rev: 1.16.5
      - name: Install nms into m2
        if: "steps.sj.outputs.cache-hit != 'true'"
        run: |
          mkdir -p $HOME/.m2/repository
          cp -a nms-build/.m2/repository/. $HOME/.m2/repository
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@main
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
