name: Build and test with Scenamatica
on:
  push:
    paths:
      - "Scenamatica/**"
  pull_request:
    paths:
      - "Scenamatica/**"
  workflow_dispatch:


permissions:
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-scenamatica-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build with Maven
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Change directory to scenamatica
        run: cd Scenamatica
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        id: sj
        with:
          java-version: 8
          distribution: zulu
          cache: maven
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2
      - uses: PeyaPeyaPeyang/nmsaction@v5
        if: "steps.sj.outputs.cache-hit != 'true'"
        with:
          rev: 1.16.5, 1.13.2
      - name: Install nms into m2
        if: "steps.sj.outputs.cache-hit != 'true'"
        run: |
          mkdir -p $HOME/.m2/repository
          cp -a nms-build/.m2/repository/. $HOME/.m2/repository
      - name: Build with Maven
        run: |
          mvn -B package --file pom.xml -D"jar.finalName=Scenamatica" -P debug
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: scenamatica
          path: ScenamaticaPlugin/target/Scenamatica.jar
          retention-days: 1
          if-no-files-found: error

  test:
    name: Self-test with Scenamatica
    runs-on: self-hosted
    needs: build
    strategy:
      matrix:
        minecraft:
          - 1.16.5
          - 1.13.2
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: scenamatica
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        id: sj
        with:
          java-version: 8
          distribution: zulu
      - name: Run Scenamatica tests
        uses: teamkun/scenamatica-action@main
        with:
          plugin: Scenamatica.jar
          minecraft: ${{ matrix.minecraft }}
          server-dir: server-${{ matrix.minecraft }}
        env:
          NO_SCENAMATICA: true
        timeout-minutes: 20
  clean:
    name: Clean up
    runs-on: self-hosted
    if: always()
    needs: test
    steps:
      - name: Clean artifacts
        if: always()
        uses: geekyeggo/delete-artifact@v2
        with:
          name: scenamatica
