name: Build and test with Scenamatica
on:
  push:
    paths:
      - "Scenamatica/**"
  pull_request:
    paths:
      - "Scenamatica/**"
  workflow_dispatch:

permissions:
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-scenamatica-${{ github.ref }}
  cancel-in-progress: true
jobs:
  setup-nms:
    name: Setup NMS
    uses: "/.github/workflows/build-nms.yml"
    secrets: inherit
    with:
      cache-name: scenamatica-nms
  build:
    name: Build with Maven
    needs: setup-nms
    uses: "/.github/workflows/build-scenamatica.yml"
    secrets: inherit
    with:
      nms-cache-name: scenamatica-nms
      artifact-name: scenamatica
  self-tests:
    name: Self-test with Scenamatica
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        include:
          - minecraft: 1.16.5
            java: 16
          - minecraft: 1.15.2
            java: 12
          - minecraft: 1.14.4
            java: 12
          - minecraft: 1.13.2
            java: 12
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: scenamatica
      - name: Run Scenamatica tests
        uses: teamkun/scenamatica-action@main
        with:
          plugin: Scenamatica.jar
          java: ${{ matrix.java }}
          minecraft: ${{ matrix.minecraft }}
          server-dir: server-${{ matrix.minecraft }}
          scenamatica: 1.1.0-pre1
          report-artifact-name: scenamatica-reports-${{ matrix.minecraft }}
          java-arguments: "-Xms8G -Xmx8G -XX:+UseG1GC -XX:+AlwaysPreTouch -XX:MaxGCPauseMillis=1000 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=60 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:-ParallelRefProcEnabled -XX:MaxTenuringThreshold=10"
        env:
          NO_SCENAMATICA: true
        timeout-minutes: 60
  cleanup:
    name: Clean up
    runs-on: self-hosted
    needs: self-tests
    steps:
      - name: Clean artifacts
        uses: geekyeggo/delete-artifact@v2
        with:
          name: scenamatica
